services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./chamilo:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chamilo
      MYSQL_USER: chamilo
      MYSQL_PASSWORD: chamilo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
